In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
import numpy as np
import os

from utils import Display

In [2]:
file_path = '/mnt/data/raydata/政策-经济-建设/各级别产业园区信息（2025.7更新）/国家级、省级、区县级产业园区数据.xlsx'
park = pd.read_excel(file_path)

In [4]:
Display(park)

Shape: (104129, 14)
Index(['级别', '产业', '产业园名称', '简介', '位置', '经度', '纬度', '省份', '城市', '区县',
       'Unnamed: 10', '更多数据请关注公众号', 'Unnamed: 12', 'Unnamed: 13'],
      dtype='object')

             Missing  Unique    Dtype
级别                 1       7   object
产业                 2      28   object
产业园名称              2  103676   object
简介                11  103262   object
位置                80    2511   object
经度               939   54531  float64
纬度               938   56203  float64
省份                80      33   object
城市              6800     438   object
区县             10207    2225   object
Unnamed: 10   104129       0  float64
更多数据请关注公众号    104127       2   object
Unnamed: 12   104129       0  float64
Unnamed: 13   104123       3   object

【col: 级别】
  - 其他: 90963 次
  - 省级: 4444 次
  - 区县级: 3866 次
  - 乡镇级: 2052 次
  - 国家级: 2045 次
----------------------------------------
【col: 产业】
  - 其他: 93644 次
  - 电子信息: 3033 次
  - 文化创意: 1058 次
  - 家电数码: 866 次
  - 农林牧渔: 751 次
----------------------------------------
【col: 产业园名称】
  - 涿州中关村和谷创新产业园: 14 次
  - 安徽青年电子商务产业园: 12 次
  - 青网科技园: 10 次
  - 阿尔法智能制造产业园: 8 次
  - 天山创谷平山产业园: 8 次
----------------------------------------
【col: 简介】
  - 货运站距离： - 高铁距离： - 港口距离： - 机场距离： - 区位介绍： - 公路运输： - 铁路运输： - 园区周边房价： - 元/㎡两居室租金： - 元/月本市住房均价： - 元/㎡园区生活配套： - 居住环境： - 商业环境： - 超市： - 百货商场： - 酒店商务： - 休闲娱乐： - 医疗： - 教育： -: 150 次
  - 货运站距离：1.成都站 18.6km 高铁距离：1.成都东站 28.1km 2.成都北站 18.7km 3.成都南站 25.6km 港口距离：1.成都西联钢铁物流港 18.8km 机场距离：1.成都双流国际机场 25.4km 区位介绍：保税区主要在西部园区，位于成都市主城区西北部，地处东经103°52′59″～103°58′57″，北纬30°43′17″～30°48′28″，与金牛区、青羊区、温江区和郫县接壤。公路运输：西部园区主要交通由“两纵四横”骨干路网及三条轨道交通组成，其中两纵为绕城高速、南北大道，四横为西芯大道(羊西线)、老成灌路、西源大道、货运大道。 铁路运输：在成都市区，离各火车站均近。园区周边房价：17758 元/㎡两居室租金：1500 元/月本市住房均价：9588 元/㎡园区生活配套：新建安置小区均按“10+1”标准同步配置了小学、幼儿园、农贸市场等公建配套设施。共建成公建配套项目约220个，包括社区服务中心、医疗卫生中心、养老助残中心等居住环境：截至2015年底，高新区已建成安置小区共计约1094万平米商业环境：各类配套齐全超市：欧尚、迪卡侬、华润万家、红旗、家乐福百货商场：万达广场(锦华店)、九方购物中心、凯德天府、苏宁广场城市奥特莱斯、王府井百货(科华店)酒店商务：成都首座万豪酒店、成都豪生大酒店、君豪酒店、成都华尔道夫酒店、三峡公寓休闲娱乐：高新文化中心开工建设、肖家河、新南、新北等一批以综合体形式集中建设的社区公建配套设施开工建设。截至2015年底，高新区已陆续建成锦城湖公园、锦江滨河公园、大源中央公园等项目，其余项目正加紧推进。医疗：成都市中西医结合医院、四川省肿瘤医院、四川省中西医结合医院教育：共建成并使用中小学、幼儿园等学校约98所。已建成蒙彼利埃小学、紫荆小学、大源Ⅷ线幼儿园、怡馨家园小学等一批学校及幼儿园。中和职中、保利心语南侧小学、中学、幼儿园等一批学校及幼儿园正在抓紧建设。: 96 次
  - 货运站距离：10.0高铁距离：5.0港口距离：90.0机场距离：60.0区位介绍：坐落于宝坻区口东镇。位于天津市偏北方，距市区60公里；距天津机场60公里；距天津港90公里；距北京70公里。紧邻津蓟高速公路及潮白河左堤路、潮阳东路、宝黑公路等一级公路。公路运输：津蓟高速公路、宝平公路、津围公路贯穿宝坻区南北；京沈高速公路、大黑林路、京唐公路横贯东西；京沈高速和津蓟高速公路在城区交汇 铁路运输：津蓟铁路途径宝坻区境内。园区周边房价：6000.0 元/㎡两居室租金：1200.0 元/月本市住房均价：15000.0 元/㎡园区生活配套：园区周边建有公寓楼可提供解决住宿问题，周边依托宝坻城区现有住房居住环境：京津新城隶属于天津市宝坻区，2006年经国务院批准设立，是天津市在滨海新区开发开放战略中重点打造的十一座新城之一。城市定位为京津唐地区重要的休闲旅游服务中心，将打造成为以休闲度假、温泉疗养、会议会展、文化教育、总部经济、商业金融为特色的现代化卫星城市。经过几年的发展，已经形成独具魅力的产业特色，为打造社会主义京津冀一体化的先行区奠定了基础。玺悦峰、景瑞悦府、中航瑞景花园、龙熙府商业环境：宝坻目前商业环境主要以日常生活型消费为主，缺少大型、综合型商业综合体超市：城区劝宝超市及周边日用超市百货商场：百货大楼、宝坻新天地商业广场、宝坻怡购商业广场、东汇广场酒店商务：京津新城帝景温泉度假村、宝坻长城宾馆、宝坻宾馆、天津宝坻京津新城凯悦酒店、天津市宝坻区开发区大酒店休闲娱乐：京津新城帝景温泉度假村、 天天娱乐音乐广场医疗：宝坻区人民医院、宝坻区中医医院、宝坻区妇幼保健院教育：宝坻一中、宝坻四中、天津财经大学珠江学院、北京科技大学天津学院、解放军军事交通学院、天津医科大学临床医学院: 28 次
  - 暂未填写: 27 次
  - 货运站距离：2.0高铁距离：3.0港口距离：30.0机场距离：15.0区位介绍：天津西青精武镇吴庄子工业园紧邻团泊大道 津晋高速入口200米附近 津文公路赛达大道与毛条路交口 距中石油桥15分钟车程公路运输：位于天津市区南部，紧邻市中心。市政府8公里，区政府35公里，天津港30公里，天津海关9公里，天津国际机场15公里，首都国际机场150公里。 铁路运输：李港铁路园区周边房价：15000.0 元/㎡两居室租金：1500.0 元/月本市住房均价：25000.0 元/㎡园区生活配套：盛兴家园小区 鑫龙商业广场 佰思哲自选超市 天之福商务酒店 赛达采摘园居住环境：恒益隆庭 盛兴家园小区 开源里 祥和园 旭辉燕南园商业环境：鑫龙商业广场 精武国际商务广场超市：乐惠万家生活超市 佰思哲自选超市 世纪家旺福超市 佳客来超市百货商场：鑫龙商业广场 精武国际商务广场酒店商务：天之福商务酒店 天津金兰福泰宾馆 鑫龙快捷酒店 天福快捷酒店休闲娱乐：津涞洗浴 赛达采摘园医疗：蓝卡诊所 南河镇生殖健康服务分中心 济民医院 牛驼子卫生所 精武镇社区卫生服务中心教育：大南河小学 天津市西青区南河镇中心小学 天津师大富家湾幼儿园孙庄分园 天津公安警官职业学院 陈台子小学: 16 次
----------------------------------------
【col: 位置】
  - 广东-深圳-宝安区: 4283 次
  - 广东-东莞-东莞市: 3073 次
  - 广东-深圳-龙岗区: 2927 次
  - 上海: 2497 次
  - 广东-深圳-龙华区: 2363 次
----------------------------------------
【col: 经度】
  - 114.699310302734: 168 次
  - 116.674522399902: 122 次
  - 108.759834289551: 114 次
  - 114.571723937988: 64 次
  - 114.391563415527: 54 次
----------------------------------------
【col: 纬度】
  - 38.280101776123: 168 次
  - 39.5265464782715: 122 次
  - 34.4364852905273: 114 次
  - 38.1434135437012: 64 次
  - 23.0922107696533: 54 次
----------------------------------------
【col: 省份】
  - 广东: 31396 次
  - 江苏: 12285 次
  - 浙江: 10719 次
  - 山东: 8276 次
  - 福建: 4052 次
----------------------------------------
【col: 城市】
  - 深圳: 11066 次
  - 广州: 5090 次
  - 佛山: 3626 次
  - 东莞: 3336 次
  - 苏州: 3193 次
----------------------------------------
【col: 区县】
  - 宝安区: 4283 次
  - 东莞市: 3073 次
  - 龙岗区: 2927 次
  - 龙华区: 2380 次
  - 南海区: 1761 次
----------------------------------------
【col: Unnamed: 10】
  (该列全为空或无有效数据)
----------------------------------------
【col: 更多数据请关注公众号】
  - 【众鲤数据网】: 1 次
  - 官网https://zldatas.com: 1 次
----------------------------------------
【col: Unnamed: 12】
  (该列全为空或无有效数据)
----------------------------------------
【col: Unnamed: 13】
  - 更多数据请关注公众号: 2 次
  - 【众鲤数据网】: 2 次
  - 官网https://zldatas.com: 2 次
----------------------------------------

In [8]:
housing_path = '/mnt/data/raydata/房产/Housing_Sale_Listing_Rent/community_p/community.parquet'
housing = pd.read_parquet(housing_path)
Display(housing)

Shape: (317229, 28)
Index(['名称', '城市', '区县', '板块', '参考均价', '环线位置', '小区地址', '物业类别', '建筑年代', '开发商',
       '房屋总数', '楼栋总数', '物业公司', '绿 化 率', '容 积 率', '物 业 费', '建筑结构', '物业办公电话',
       '产权描述', '供水', '供暖', '供电', '燃气费', '供热费', '停车位', '停车费用', 'baidu_coord_x',
       'baidu_coord_y'],
      dtype='object')

               Missing  Unique    Dtype
名称                   0  278183   object
城市                   0      97   object
区县                   0    1020   object
板块                1243    5104   object
参考均价             77819   46637  float64
环线位置            263662      32   object
小区地址                12  301569   object
物业类别              9056    1372   object
建筑年代            123145    2603   object
开发商             132682   47763   object
房屋总数                76    6035   object
楼栋总数                66     523   object
物业公司            150734   39031   object
绿 化 率           107739    2343   object
容 积 率           106252    1342  float64
物 业 费           111916    9856   object
建筑结构             71152      15   object
物业办公电话          270728   18847   object
产权描述              9689    1496   object
供水               85941       3   object
供暖              183151       7   object
供电               83671       3   object
燃气费             117869    6131   object
供热费             228069    3579   object
停车位             124146    4735  float64
停车费用            135166    3799   object
baidu_coord_x        0  314556  float64
baidu_coord_y        0  314183  float64

【col: 名称】
  - 阳光花园: 64 次
  - 幸福家园: 63 次
  - 锦绣花园: 59 次
  - 粮食局宿舍: 42 次
  - 和谐家园: 41 次
----------------------------------------
【col: 城市】
  - 上海: 22092 次
  - 成都: 18260 次
  - 北京: 10945 次
  - 重庆: 10104 次
  - 苏州: 8625 次
----------------------------------------
【col: 区县】
  - 浦东: 3659 次
  - 顺德: 2216 次
  - 城关区: 2083 次
  - 鼓楼区: 2011 次
  - 金水: 1893 次
----------------------------------------
【col: 板块】
  - 老城区: 2106 次
  - 火车站: 1624 次
  - 魏都区: 1113 次
  - 都江堰: 1101 次
  - 海城区: 1060 次
----------------------------------------
【col: 参考均价】
  - 60000.0: 57 次
  - 50000.0: 51 次
  - 55000.0: 43 次
  - 68000.0: 41 次
  - 40000.0: 38 次
----------------------------------------
【col: 环线位置】
  - 外环外: 8494 次
  - 内环内: 7878 次
  - 二至三环: 6307 次
  - 内环至中环: 4184 次
  - 中环至外环: 3638 次
----------------------------------------
【col: 小区地址】
  - 兴华中路: 56 次
  - 太极大道: 50 次
  - 浔峰洲路8号: 37 次
  - 顺江大道: 34 次
  - 黎明路: 33 次
----------------------------------------
【col: 物业类别】
  - 普通住宅: 211943 次
  - 普通住宅/底商: 14259 次
  - 普通住宅/别墅: 10379 次
  - 普通住宅/商业/底商: 8421 次
  - 普通住宅/商业: 8348 次
----------------------------------------
【col: 建筑年代】
  - 2000年: 6292 次
  - 1998年: 4064 次
  - 1995年: 2804 次
  - 2005年: 2688 次
  - 1999年: 2418 次
----------------------------------------
【col: 开发商】
  - 无开发商: 18551 次
  - 无: 6910 次
  - 陕西亿润经贸有限公司: 3315 次
  - 重庆汇东房地产开发有限公司: 2835 次
  - 物业和度娘都不知道开发商名称: 2033 次
----------------------------------------
【col: 房屋总数】
  - 1户: 12901 次
  - 2户: 5096 次
  - 24户: 3656 次
  - 36户: 3232 次
  - 48户: 3175 次
----------------------------------------
【col: 楼栋总数】
  - 1栋: 78373 次
  - 2栋: 36822 次
  - 3栋: 25672 次
  - 4栋: 20412 次
  - 5栋: 15426 次
----------------------------------------
【col: 物业公司】
  - 无物业管理服务: 11009 次
  - 业主自筹物业: 6282 次
  - 街道办事处（居委会）代管物业: 5808 次
  - 私人承办物业: 2122 次
  - 小区物业: 1931 次
----------------------------------------
【col: 绿 化 率】
  - 30%: 47345 次
  - 35%: 27593 次
  - 20%: 23248 次
  - 10%: 14883 次
  - 40%: 13593 次
----------------------------------------
【col: 容 积 率】
  - 2.0: 28779 次
  - 3.0: 16786 次
  - 1.5: 12475 次
  - 2.5: 11472 次
  - 1.0: 11066 次
----------------------------------------
【col: 物 业 费】
  - 0.5元/月/㎡: 21464 次
  - 1元/月/㎡: 13911 次
  - 1.2元/月/㎡: 10067 次
  - 0.8元/月/㎡: 9540 次
  - 1.5元/月/㎡: 8297 次
----------------------------------------
【col: 建筑结构】
  - 板楼: 119530 次
  - 塔板结合: 34985 次
  - 塔楼: 26571 次
  - 板楼/塔板结合: 22147 次
  - 塔楼/板楼: 14895 次
----------------------------------------
【col: 物业办公电话】
  - 无: 20954 次
  - 暂无资料: 492 次
  - 暂无: 269 次
  - -: 259 次
  - 022-27022093: 110 次
----------------------------------------
【col: 产权描述】
  - 商品房: 222032 次
  - 商品房/使用权: 12376 次
  - 商品房/私产: 10485 次
  - 商品房/已购公房: 9394 次
  - 商品房/房改房: 6117 次
----------------------------------------
【col: 供水】
  - 民水: 189994 次
  - 商水/民水: 34414 次
  - 商水: 6880 次
----------------------------------------
【col: 供暖】
  - 集中供暖: 75336 次
  - 自采暖: 49137 次
  - 集中供暖/自采暖: 8270 次
  - 无供暖: 918 次
  - 自采暖/无供暖: 369 次
----------------------------------------
【col: 供电】
  - 民电: 191088 次
  - 商电/民电: 35674 次
  - 商电: 6796 次
----------------------------------------
【col: 燃气费】
  - 3元/m³: 13588 次
  - 2.61元/m³: 10025 次
  - 3.5元/m³: 6700 次
  - 3.45元/m³: 6431 次
  - 1.98元/m³: 6425 次
----------------------------------------
【col: 供热费】
  - 25元/㎡: 8222 次
  - 30元/㎡: 7198 次
  - 22元/㎡: 6095 次
  - 30.4元/㎡: 4161 次
  - 26元/㎡: 4059 次
----------------------------------------
【col: 停车位】
  - 100.0: 13648 次
  - 200.0: 13076 次
  - 50.0: 9317 次
  - 300.0: 8328 次
  - 20.0: 6193 次
----------------------------------------
【col: 停车费用】
  - 150: 21294 次
  - 300: 20479 次
  - 200: 19364 次
  - 100: 17829 次
  - 暂无: 15528 次
----------------------------------------
【col: baidu_coord_x】
  - 115.9501: 30 次
  - 115.950135: 21 次
  - 115.8989: 17 次
  - 115.9101: 15 次
  - 115.922: 13 次
----------------------------------------
【col: baidu_coord_y】
  - 28.55: 30 次
  - 28.550035: 21 次
  - 28.6573: 16 次
  - 28.6924: 15 次
  - 28.6366: 13 次
----------------------------------------

In [9]:
housing_path = '/mnt/data/raydata/房产/Housing_Sale_Listing_Rent/listing_p/北京.parquet'
housing = pd.read_parquet(housing_path)
Display(housing)

Shape: (261159, 35)
Index(['城市', '区域', '板块', '环线', '小区名称', '价格', '单价', '链家编号', '看房时间', '房屋户型',
       '所在楼层', '建筑面积', '套内面积', '房屋朝向', '建筑结构', '装修情况', '梯户比例', '配备电梯', '别墅类型',
       '挂牌时间', '交易权属', '上次交易', '房屋用途', '房屋年限', '产权所属', '抵押信息', '房本备件', '房源标签',
       '核心卖点', '户型介绍', '周边配套', '交通出行', 'lon', 'lat', '年份'],
      dtype='object')

      Missing  Unique    Dtype
城市          0       1   object
区域          0      17   object
板块          0     255   object
环线      21115       6   object
小区名称        0    8024   object
价格          0    2818  float64
单价          0   99366   object
链家编号        0  261159  float64
看房时间        0       4   object
房屋户型    18573     549   object
所在楼层    16788     234   object
建筑面积    16788   21777   object
套内面积   161770   16228   object
房屋朝向    16788     232   object
建筑结构    18573       7   object
装修情况    18573       4   object
梯户比例    19988     431   object
配备电梯    24918       2   object
别墅类型   260732       4   object
挂牌时间     1193    1889   object
交易权属        0       9   object
上次交易       50    9690   object
房屋用途        0      15   object
房屋年限      186       3   object
产权所属        0       2   object
抵押信息   261159       0  float64
房本备件        0       2   object
房源标签     3069      35   object
核心卖点    54934  173123   object
户型介绍   152751   85007   object
周边配套   130661   51148   object
交通出行   125947   49138   object
lon         0    8192  float64
lat         0    8171  float64
年份       1193       8   object

【col: 城市】
  - 北京: 261159 次
----------------------------------------
【col: 区域】
  - 朝阳: 58859 次
  - 丰台: 29637 次
  - 海淀: 24887 次
  - 通州: 21044 次
  - 大兴: 20854 次
----------------------------------------
【col: 板块】
  - 长阳: 6974 次
  - 回龙观: 5837 次
  - 顺义城: 5390 次
  - 望京: 5380 次
  - 良乡: 4173 次
----------------------------------------
【col: 环线】
  - 五至六环: 86968 次
  - 四至五环: 41179 次
  - 三至四环: 36417 次
  - 六环外: 33266 次
  - 二至三环: 31178 次
----------------------------------------
【col: 小区名称】
  - 远洋山水: 531 次
  - 荣丰2008: 527 次
  - 天通苑东一区: 523 次
  - 龙湖长城源著2号院: 517 次
  - 芍药居北里: 494 次
----------------------------------------
【col: 价格】
  - 450.0: 1974 次
  - 550.0: 1686 次
  - 420.0: 1667 次
  - 320.0: 1663 次
  - 330.0: 1647 次
----------------------------------------
【col: 单价】
  - 100000元/平米: 112 次
  - 50000元/平米: 43 次
  - 125000元/平米: 41 次
  - 45455元/平米: 39 次
  - 62500元/平米: 37 次
----------------------------------------
【col: 链家编号】
  - 101091978877.0: 1 次
  - 101118266406.0: 1 次
  - 101118266246.0: 1 次
  - 101118266261.0: 1 次
  - 101118266294.0: 1 次
----------------------------------------
【col: 看房时间】
  - 提前预约随时可看: 182031 次
  - 有租户需预约: 56773 次
  - 下班后可看: 13446 次
  - 只周末可看: 8909 次
----------------------------------------
【col: 房屋户型】
  - 2室1厅1厨1卫: 97118 次
  - 1室1厅1厨1卫: 33534 次
  - 3室1厅1厨1卫: 24243 次
  - 3室2厅1厨2卫: 18071 次
  - 3室1厅1厨2卫: 11207 次
----------------------------------------
【col: 所在楼层】
  - 中楼层 (共6层): 22672 次
  - 顶层 (共6层): 17807 次
  - 高楼层 (共6层): 14766 次
  - 低楼层 (共6层): 9942 次
  - 底层 (共6层): 9504 次
----------------------------------------
【col: 建筑面积】
  - 57.2㎡: 164 次
  - 58.1㎡: 163 次
  - 57.9㎡: 156 次
  - 58㎡: 145 次
  - 57.4㎡: 139 次
----------------------------------------
【col: 套内面积】
  - 50㎡: 103 次
  - 68.32㎡: 96 次
  - 71.59㎡: 86 次
  - 60㎡: 78 次
  - 65㎡: 78 次
----------------------------------------
【col: 房屋朝向】
  - 南 北: 116839 次
  - 南: 39504 次
  - 东南: 10864 次
  - 东: 10003 次
  - 西南: 9873 次
----------------------------------------
【col: 建筑结构】
  - 钢混结构: 149331 次
  - 混合结构: 90369 次
  - 砖混结构: 2157 次
  - 未知结构: 322 次
  - 钢结构: 198 次
----------------------------------------
【col: 装修情况】
  - 精装: 109998 次
  - 简装: 84109 次
  - 其他: 43918 次
  - 毛坯: 4561 次
----------------------------------------
【col: 梯户比例】
  - 一梯两户: 75937 次
  - 一梯三户: 39150 次
  - 两梯四户: 18483 次
  - 一梯四户: 11975 次
  - 两梯八户: 10658 次
----------------------------------------
【col: 配备电梯】
  - 有: 143072 次
  - 无: 93169 次
----------------------------------------
【col: 别墅类型】
  - 联排: 168 次
  - 独栋: 134 次
  - 叠拼: 108 次
  - 双拼: 17 次
----------------------------------------
【col: 挂牌时间】
  - 2023-02-16: 1637 次
  - 2023-02-10: 1601 次
  - 2023-02-09: 1596 次
  - 2023-02-15: 1511 次
  - 2023-02-17: 1483 次
----------------------------------------
【col: 交易权属】
  - 商品房: 198908 次
  - 已购公房: 35267 次
  - 二类经济适用房: 7987 次
  - 一类经济适用房: 6566 次
  - 限价商品房: 6229 次
----------------------------------------
【col: 上次交易】
  - 2004-06-30: 185 次
  - 2016-09-29: 181 次
  - 2016-10-31: 171 次
  - 2016-10-18: 167 次
  - 2017-03-30: 162 次
----------------------------------------
【col: 房屋用途】
  - 普通住宅: 246217 次
  - 商业办公类: 8612 次
  - 公寓: 2869 次
  - 车库: 1785 次
  - 别墅: 556 次
----------------------------------------
【col: 房屋年限】
  - 满五年: 190247 次
  - 满两年: 42773 次
  - 未满两年: 27953 次
----------------------------------------
【col: 产权所属】
  - 非共有: 228758 次
  - 共有: 32401 次
----------------------------------------
【col: 抵押信息】
  (该列全为空或无有效数据)
----------------------------------------
【col: 房本备件】
  - 已上传房本照片: 261131 次
  - 未上传房本照片: 28 次
----------------------------------------
【col: 房源标签】
  - VR看装修、房本满五年: 33231 次
  - VR房源、房本满五年: 27265 次
  - 地铁、VR看装修、房本满五年: 26672 次
  - 地铁、VR房源、房本满五年: 23015 次
  - 地铁、房本满五年: 16703 次
----------------------------------------
【col: 核心卖点】
  - 此房满五唯一，南北通透格局，楼层好，视野宽阔，采光充足: 115 次
  - 此房满五唯一，南北通透格局，楼层好，视野宽阔，采光充足。: 97 次
  - 格局方正，无浪费面积，采光充足，视野开阔。: 56 次
  - 集中供暖、生活便利、出行方便、诚心出售: 50 次
  - 此房满五年唯一，南北通透格局，楼层好，视野宽阔，采光充足: 45 次
----------------------------------------
【col: 户型介绍】
  - 本房的户型很合理，格局好，楼层好，采光很不错，视野开阔，居住舒适。: 190 次
  - 本房的户型很合理，没有浪费面积，楼层好，采光很不错，视野开阔。: 50 次
  - 本房户型方正，南北通透，前后无任何遮挡，视野开阔，采光充足，室内格局设计合理，客厅和主卧朝南，次卧朝北跟主卧相对，通风效果好，居住舒适: 34 次
  - 此房是南向的二居室，主卧、次卧和客厅都朝南，采光好没有遮挡。: 25 次
  - 户型方正无浪费面积，无任何遮挡，看房效果很不错，房屋功能间齐全: 25 次
----------------------------------------
【col: 周边配套】
  - 小区南门往东是天通艺园公园、苏宁电器、大物美、国泰百货，再往东就是白坊菜市场，银行有农行、工行、建行等。医院：天通苑医院，120急救医院，清华长庚医院，航空医院天通苑分院。: 158 次
  - 出小区东侧过天桥就有清华长庚三甲医院，华联商场，家乐福，百安居，万达国际影城，翠微百货，华夏银行，建设银行，广发银行，农业银行，邮政储蓄等，出行购物都很方便，生活配套一应俱全。: 108 次
  - 生活购物方便,有首航，百姓大润发，润福霖，奥宇农贸市场，传统集市。农商银行，农业银行，邮政储蓄银行。: 87 次
  - 小区配套成熟，广安门中医院，大兴仁和医院，银行有工商银行，建设银行，北京银行，商场有百联青城，绿地缤纷城等。: 83 次
  - 小区东门外就是上河湾公园，紧挨着白河边，日常工作之余或茶余饭后，小区业主都会去公园遛弯，跑步健身。河边配套的跑步步道平坦舒适，深得跑步爱好者的偏爱。春暖花开，河冰已开始消融，这里就会鸟语花香，欢声笑语！欢迎随时致电详询！: 82 次
----------------------------------------
【col: 交通出行】
  - 通11和通12可到九棵树地铁，19路，36路、316可到果园和北苑地铁，552可到6号线北运河西，582可到地铁草房站，669直达国贸，早班车807直达大北窑；自驾车出行向南到京哈高速5.5公里（来源于百度地图），到新建的广渠路2.6公里（来源于百度地图: 145 次
  - 出行有直达东直门的古北水镇专线，全程高速，票价48元/每位，到密云县城有51路公交车，自驾出行开车3.8公里可到达京承高速司马台入口。: 145 次
  - 小区距离京港澳高速阎村口3.8公里，距离六环阎村口3.6公里（数据来自百度地图），驾车方便。小区北门距离燕房线阎村站190米（数据来自百度地图），小区的北边是紫草坞路口公交站，途经的公交车有952、901、836、839、房14、房15、房38、房42等出行方便: 107 次
  - 小区北侧是自行车专用通道，北侧有出入口，起点西二旗北路，终点回龙观，途径龙泽地铁站，回龙观地铁站，出行很方便。公交线路：307路;371路;963路;快速直达专线14路;快速直达专线21路;专29路，方便到达上地，西二旗，安宁庄，霍营，巴沟，马连洼等地。: 104 次
  - 小区位于东四环和五环中间，朝阳路与朝阳北路之间，青年路边上，地铁是6号线-青年路站；往南是朝阳路和京通快速路，往北是朝阳北路和姚家园路，无论开车出行，还是坐公交、地铁，都便利。: 98 次
----------------------------------------
【col: lon】
  - 116.247008: 531 次
  - 116.343245: 527 次
  - 116.43942: 523 次
  - 117.273243: 517 次
  - 116.441781: 494 次
----------------------------------------
【col: lat】
  - 39.906426: 531 次
  - 39.900529: 527 次
  - 40.072066: 523 次
  - 40.667358: 517 次
  - 39.991956: 494 次
----------------------------------------
【col: 年份】
  - 2023: 133246 次
  - 2022: 102997 次
  - 2021: 12168 次
  - 2024: 9499 次
  - 2020: 1364 次
----------------------------------------

In [10]:
housing_path = '/mnt/data/raydata/房产/Housing_Sale_Listing_Rent/sale_p/北京.parquet'
housing = pd.read_parquet(housing_path)
Display(housing)

Shape: (1045734, 35)
Index(['城市', '区域', '商圈', '小区', '挂牌时间', '成交日期', '成交价（万）', '挂牌价格（万）', '成交周期（天）',
       '调价（次）', '带看（次）', '关注（人）', '浏览（次）', '房屋户型', '所在楼层', '建筑面积（㎡）', '户型结构',
       '套内面积（㎡）', '建筑类型', '房屋朝向', '建成年代', '装修情况', '建筑结构', '供暖方式', '梯户比例',
       '产权年限', '配备电梯', '链家编号', '交易权属', '房屋用途', '房屋年限', '房权所属', '经度', '纬度',
       '年份'],
      dtype='object')

         Missing   Unique    Dtype
城市             0        1   object
区域             0       17   object
商圈             0      258   object
小区             0     8473   object
挂牌时间       20030     5017   object
成交日期           0     5136   object
成交价（万）    484579     2156  float64
挂牌价格（万）    65548     4533  float64
成交周期（天）   200420     2922   object
调价（次）          0       38  float64
带看（次）     243366      489  float64
关注（人）          0      976  float64
浏览（次）     332302    22504  float64
房屋户型           0      500   object
所在楼层           0      273   object
建筑面积（㎡）     1622    25478   object
户型结构      220086        5   object
套内面积（㎡）   712954    18631   object
建筑类型       11300        4   object
房屋朝向       48164      260   object
建成年代        6964       88   object
装修情况           0        4   object
建筑结构           0        7   object
供暖方式       11577        2   object
梯户比例       19933      547   object
产权年限      350508        4   object
配备电梯        6169        2   object
链家编号           0  1045734   object
交易权属           4       17   object
房屋用途           1       21   object
房屋年限      295947        2   object
房权所属      376748        2   object
经度             0     8676  float64
纬度             0     8639  float64
年份             0       22  float64

【col: 城市】
  - 北京: 1045734 次
----------------------------------------
【col: 区域】
  - 朝阳: 341890 次
  - 丰台: 147325 次
  - 海淀: 114188 次
  - 昌平: 102219 次
  - 大兴: 78442 次
----------------------------------------
【col: 商圈】
  - 回龙观: 35976 次
  - 望京: 27616 次
  - 天通苑: 21404 次
  - 北苑: 17665 次
  - 常营: 17241 次
----------------------------------------
【col: 小区】
  - 芍药居北里: 2872 次
  - 新龙城: 2681 次
  - 天通苑东一区: 2638 次
  - 天通西苑三区: 2198 次
  - 东亚上北中心: 2146 次
----------------------------------------
【col: 挂牌时间】
  - 2016.03.01: 5855 次
  - 2015.12.01: 5160 次
  - 2015.11.01: 4465 次
  - 2015.05.01: 4433 次
  - 2015.07.01: 4316 次
----------------------------------------
【col: 成交日期】
  - 2016.03: 5836 次
  - 2016.08: 5694 次
  - 2020.05: 5592 次
  - 2016.07: 5337 次
  - 2015.12: 5120 次
----------------------------------------
【col: 成交价（万）】
  - 300.0: 4085 次
  - 320.0: 3426 次
  - 350.0: 3377 次
  - 400.0: 3374 次
  - 280.0: 3362 次
----------------------------------------
【col: 挂牌价格（万）】
  - 350.0: 9755 次
  - 320.0: 9645 次
  - 450.0: 9346 次
  - 330.0: 9258 次
  - 360.0: 8845 次
----------------------------------------
【col: 成交周期（天）】
  - 1: 176847 次
  - 2: 11544 次
  - 3: 11293 次
  - 4: 11288 次
  - 5: 10905 次
----------------------------------------
【col: 调价（次）】
  - 1.0: 480353 次
  - 0.0: 386294 次
  - 2.0: 63285 次
  - 3.0: 44201 次
  - 4.0: 28081 次
----------------------------------------
【col: 带看（次）】
  - 0.0: 358789 次
  - 1.0: 24168 次
  - 2.0: 20581 次
  - 3.0: 19020 次
  - 4.0: 17662 次
----------------------------------------
【col: 关注（人）】
  - 0.0: 244184 次
  - 1.0: 44360 次
  - 2.0: 33945 次
  - 3.0: 29937 次
  - 4.0: 27089 次
----------------------------------------
【col: 浏览（次）】
  - 1.0: 78198 次
  - 2.0: 23631 次
  - 3.0: 11466 次
  - 4.0: 5813 次
  - 5.0: 3957 次
----------------------------------------
【col: 房屋户型】
  - 2室1厅1厨1卫: 402403 次
  - 1室1厅1厨1卫: 176871 次
  - 3室1厅1厨1卫: 88121 次
  - 3室2厅1厨2卫: 71043 次
  - 2室2厅1厨1卫: 53541 次
----------------------------------------
【col: 所在楼层】
  - 中楼层(共6层): 106964 次
  - 顶层(共6层): 61150 次
  - 高楼层(共6层): 59394 次
  - 低楼层(共6层): 49123 次
  - 底层(共6层): 42533 次
----------------------------------------
【col: 建筑面积（㎡）】
  - 89: 1908 次
  - 60: 1702 次
  - 58: 1679 次
  - 57: 1544 次
  - 61: 1197 次
----------------------------------------
【col: 户型结构】
  - 平层: 796236 次
  - 复式: 16623 次
  - 跃层: 10009 次
  - 错层: 1923 次
  - Loft: 857 次
----------------------------------------
【col: 套内面积（㎡）】
  - 50: 1018 次
  - 1: 983 次
  - 40: 629 次
  - 60: 610 次
  - 45: 480 次
----------------------------------------
【col: 建筑类型】
  - 板楼: 591379 次
  - 塔楼: 252757 次
  - 板塔结合: 189540 次
  - 平房: 758 次
----------------------------------------
【col: 房屋朝向】
  - 南北: 428264 次
  - 南: 176516 次
  - 东南: 61647 次
  - 东: 48123 次
  - 西南: 42528 次
----------------------------------------
【col: 建成年代】
  - 2004: 66609 次
  - 2005: 61842 次
  - 2003: 53095 次
  - 2006: 46641 次
  - 2007: 44055 次
----------------------------------------
【col: 装修情况】
  - 精装: 435386 次
  - 简装: 308839 次
  - 其他: 282391 次
  - 毛坯: 19118 次
----------------------------------------
【col: 建筑结构】
  - 钢混结构: 653709 次
  - 混合结构: 373411 次
  - 砖混结构: 16388 次
  - 未知结构: 1090 次
  - 钢结构: 655 次
----------------------------------------
【col: 供暖方式】
  - 集中供暖: 869152 次
  - 自供暖: 165005 次
----------------------------------------
【col: 梯户比例】
  - 一梯两户: 292280 次
  - 一梯三户: 170315 次
  - 两梯四户: 69031 次
  - 两梯八户: 63216 次
  - 一梯四户: 47544 次
----------------------------------------
【col: 产权年限】
  - 70年: 665273 次
  - 50年: 17324 次
  - 40年: 10718 次
  - 未知: 1911 次
----------------------------------------
【col: 配备电梯】
  - 有: 640799 次
  - 无: 398766 次
----------------------------------------
【col: 链家编号】
  - 101000116304: 1 次
  - 101121817864: 1 次
  - 101121816878: 1 次
  - 101121817096: 1 次
  - 101121817203: 1 次
----------------------------------------
【col: 交易权属】
  - 商品房: 915499 次
  - 已购公房: 74298 次
  - 二类经济适用房: 14284 次
  - 一类经济适用房: 12129 次
  - 央产房: 11777 次
----------------------------------------
【col: 房屋用途】
  - 普通住宅: 990676 次
  - 商业办公类: 30457 次
  - 车库: 10993 次
  - 公寓: 7882 次
  - 别墅: 3219 次
----------------------------------------
【col: 房屋年限】
  - 满五年: 615290 次
  - 满两年: 134497 次
----------------------------------------
【col: 房权所属】
  - 非共有: 594218 次
  - 共有: 74768 次
----------------------------------------
【col: 经度】
  - 116.441781: 2872 次
  - 116.330198: 2681 次
  - 116.43942: 2638 次
  - 116.416156: 2198 次
  - 116.347998: 2149 次
----------------------------------------
【col: 纬度】
  - 39.991956: 2872 次
  - 40.074228: 2681 次
  - 40.072066: 2638 次
  - 40.082585: 2198 次
  - 40.087773: 2146 次
----------------------------------------
【col: 年份】
  - 2016.0: 153195 次
  - 2020.0: 121226 次
  - 2018.0: 106171 次
  - 2019.0: 105341 次
  - 2015.0: 102265 次
----------------------------------------

In [ ]:
housing_path = '/mnt/data/raydata/房产/城市二手房房价数据2010-2025/城市二手房房价数据2010-2025年.xlsx'
housing = pd.read_excel(housing_path)
Display(housing)