# 1.Loading Data

### Industrial Park

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
file_path = '/mnt/data/raydata/政策-经济-建设/各级别产业园区信息（2025.7更新）/国家级、省级、区县级产业园区数据.xlsx'
df = pd.read_excel(file_path)

In [4]:
def Display(df):
    print(f"Shape: {df.shape}")
    print(df.columns)
    missing_counts = df.isnull().sum()
    unique_counts = df.nunique()
    summary_df = pd.DataFrame({
        'Missing': missing_counts,
        'Unique': unique_counts,
        'Dtype': df.dtypes
    })
    display(summary_df)

    for col in df.columns:
        print(f"【col: {col}】")
        top_5 = df[col].value_counts().head(5)
        
        if top_5.empty:
            print("  (该列全为空或无有效数据)")
        else:
            for val, count in top_5.items():
                print(f"  - {val}: {count} 次")
        print("-" * 40)

In [5]:
Display(df)

Shape: (104129, 14)
Index(['级别', '产业', '产业园名称', '简介', '位置', '经度', '纬度', '省份', '城市', '区县',
       'Unnamed: 10', '更多数据请关注公众号', 'Unnamed: 12', 'Unnamed: 13'],
      dtype='object')

             Missing  Unique    Dtype
级别                 1       7   object
产业                 2      28   object
产业园名称              2  103676   object
简介                11  103262   object
位置                80    2511   object
经度               939   54531  float64
纬度               938   56203  float64
省份                80      33   object
城市              6800     438   object
区县             10207    2225   object
Unnamed: 10   104129       0  float64
更多数据请关注公众号    104127       2   object
Unnamed: 12   104129       0  float64
Unnamed: 13   104123       3   object

【col: 级别】
  - 其他: 90963 次
  - 省级: 4444 次
  - 区县级: 3866 次
  - 乡镇级: 2052 次
  - 国家级: 2045 次
----------------------------------------
【col: 产业】
  - 其他: 93644 次
  - 电子信息: 3033 次
  - 文化创意: 1058 次
  - 家电数码: 866 次
  - 农林牧渔: 751 次
----------------------------------------
【col: 产业园名称】
  - 涿州中关村和谷创新产业园: 14 次
  - 安徽青年电子商务产业园: 12 次
  - 青网科技园: 10 次
  - 阿尔法智能制造产业园: 8 次
  - 天山创谷平山产业园: 8 次
----------------------------------------
【col: 简介】
  - 货运站距离： - 高铁距离： - 港口距离： - 机场距离： - 区位介绍： - 公路运输： - 铁路运输： - 园区周边房价： - 元/㎡两居室租金： - 元/月本市住房均价： - 元/㎡园区生活配套： - 居住环境： - 商业环境： - 超市： - 百货商场： - 酒店商务： - 休闲娱乐： - 医疗： - 教育： -: 150 次
  - 货运站距离：1.成都站 18.6km 高铁距离：1.成都东站 28.1km 2.成都北站 18.7km 3.成都南站 25.6km 港口距离：1.成都西联钢铁物流港 18.8km 机场距离：1.成都双流国际机场 25.4km 区位介绍：保税区主要在西部园区，位于成都市主城区西北部，地处东经103°52′59″～103°58′57″，北纬30°43′17″～30°48′28″，与金牛区、青羊区、温江区和郫县接壤。公路运输：西部园区主要交通由“两纵四横”骨干路网及三条轨道交通组成，其中两纵为绕城高速、南北大道，四横为西芯大道(羊西线)、老成灌路、西源大道、货运大道。 铁路运输：在成都市区，离各火车站均近。园区周边房价：17758 元/㎡两居室租金：1500 元/月本市住房均价：9588 元/㎡园区生活配套：新建安置小区均按“10+1”标准同步配置了小学、幼儿园、农贸市场等公建配套设施。共建成公建配套项目约220个，包括社区服务中心、医疗卫生中心、养老助残中心等居住环境：截至2015年底，高新区已建成安置小区共计约1094万平米商业环境：各类配套齐全超市：欧尚、迪卡侬、华润万家、红旗、家乐福百货商场：万达广场(锦华店)、九方购物中心、凯德天府、苏宁广场城市奥特莱斯、王府井百货(科华店)酒店商务：成都首座万豪酒店、成都豪生大酒店、君豪酒店、成都华尔道夫酒店、三峡公寓休闲娱乐：高新文化中心开工建设、肖家河、新南、新北等一批以综合体形式集中建设的社区公建配套设施开工建设。截至2015年底，高新区已陆续建成锦城湖公园、锦江滨河公园、大源中央公园等项目，其余项目正加紧推进。医疗：成都市中西医结合医院、四川省肿瘤医院、四川省中西医结合医院教育：共建成并使用中小学、幼儿园等学校约98所。已建成蒙彼利埃小学、紫荆小学、大源Ⅷ线幼儿园、怡馨家园小学等一批学校及幼儿园。中和职中、保利心语南侧小学、中学、幼儿园等一批学校及幼儿园正在抓紧建设。: 96 次
  - 货运站距离：10.0高铁距离：5.0港口距离：90.0机场距离：60.0区位介绍：坐落于宝坻区口东镇。位于天津市偏北方，距市区60公里；距天津机场60公里；距天津港90公里；距北京70公里。紧邻津蓟高速公路及潮白河左堤路、潮阳东路、宝黑公路等一级公路。公路运输：津蓟高速公路、宝平公路、津围公路贯穿宝坻区南北；京沈高速公路、大黑林路、京唐公路横贯东西；京沈高速和津蓟高速公路在城区交汇 铁路运输：津蓟铁路途径宝坻区境内。园区周边房价：6000.0 元/㎡两居室租金：1200.0 元/月本市住房均价：15000.0 元/㎡园区生活配套：园区周边建有公寓楼可提供解决住宿问题，周边依托宝坻城区现有住房居住环境：京津新城隶属于天津市宝坻区，2006年经国务院批准设立，是天津市在滨海新区开发开放战略中重点打造的十一座新城之一。城市定位为京津唐地区重要的休闲旅游服务中心，将打造成为以休闲度假、温泉疗养、会议会展、文化教育、总部经济、商业金融为特色的现代化卫星城市。经过几年的发展，已经形成独具魅力的产业特色，为打造社会主义京津冀一体化的先行区奠定了基础。玺悦峰、景瑞悦府、中航瑞景花园、龙熙府商业环境：宝坻目前商业环境主要以日常生活型消费为主，缺少大型、综合型商业综合体超市：城区劝宝超市及周边日用超市百货商场：百货大楼、宝坻新天地商业广场、宝坻怡购商业广场、东汇广场酒店商务：京津新城帝景温泉度假村、宝坻长城宾馆、宝坻宾馆、天津宝坻京津新城凯悦酒店、天津市宝坻区开发区大酒店休闲娱乐：京津新城帝景温泉度假村、 天天娱乐音乐广场医疗：宝坻区人民医院、宝坻区中医医院、宝坻区妇幼保健院教育：宝坻一中、宝坻四中、天津财经大学珠江学院、北京科技大学天津学院、解放军军事交通学院、天津医科大学临床医学院: 28 次
  - 暂未填写: 27 次
  - 货运站距离：2.0高铁距离：3.0港口距离：30.0机场距离：15.0区位介绍：天津西青精武镇吴庄子工业园紧邻团泊大道 津晋高速入口200米附近 津文公路赛达大道与毛条路交口 距中石油桥15分钟车程公路运输：位于天津市区南部，紧邻市中心。市政府8公里，区政府35公里，天津港30公里，天津海关9公里，天津国际机场15公里，首都国际机场150公里。 铁路运输：李港铁路园区周边房价：15000.0 元/㎡两居室租金：1500.0 元/月本市住房均价：25000.0 元/㎡园区生活配套：盛兴家园小区 鑫龙商业广场 佰思哲自选超市 天之福商务酒店 赛达采摘园居住环境：恒益隆庭 盛兴家园小区 开源里 祥和园 旭辉燕南园商业环境：鑫龙商业广场 精武国际商务广场超市：乐惠万家生活超市 佰思哲自选超市 世纪家旺福超市 佳客来超市百货商场：鑫龙商业广场 精武国际商务广场酒店商务：天之福商务酒店 天津金兰福泰宾馆 鑫龙快捷酒店 天福快捷酒店休闲娱乐：津涞洗浴 赛达采摘园医疗：蓝卡诊所 南河镇生殖健康服务分中心 济民医院 牛驼子卫生所 精武镇社区卫生服务中心教育：大南河小学 天津市西青区南河镇中心小学 天津师大富家湾幼儿园孙庄分园 天津公安警官职业学院 陈台子小学: 16 次
----------------------------------------
【col: 位置】
  - 广东-深圳-宝安区: 4283 次
  - 广东-东莞-东莞市: 3073 次
  - 广东-深圳-龙岗区: 2927 次
  - 上海: 2497 次
  - 广东-深圳-龙华区: 2363 次
----------------------------------------
【col: 经度】
  - 114.699310302734: 168 次
  - 116.674522399902: 122 次
  - 108.759834289551: 114 次
  - 114.571723937988: 64 次
  - 114.391563415527: 54 次
----------------------------------------
【col: 纬度】
  - 38.280101776123: 168 次
  - 39.5265464782715: 122 次
  - 34.4364852905273: 114 次
  - 38.1434135437012: 64 次
  - 23.0922107696533: 54 次
----------------------------------------
【col: 省份】
  - 广东: 31396 次
  - 江苏: 12285 次
  - 浙江: 10719 次
  - 山东: 8276 次
  - 福建: 4052 次
----------------------------------------
【col: 城市】
  - 深圳: 11066 次
  - 广州: 5090 次
  - 佛山: 3626 次
  - 东莞: 3336 次
  - 苏州: 3193 次
----------------------------------------
【col: 区县】
  - 宝安区: 4283 次
  - 东莞市: 3073 次
  - 龙岗区: 2927 次
  - 龙华区: 2380 次
  - 南海区: 1761 次
----------------------------------------
【col: Unnamed: 10】
  (该列全为空或无有效数据)
----------------------------------------
【col: 更多数据请关注公众号】
  - 【众鲤数据网】: 1 次
  - 官网https://zldatas.com: 1 次
----------------------------------------
【col: Unnamed: 12】
  (该列全为空或无有效数据)
----------------------------------------
【col: Unnamed: 13】
  - 更多数据请关注公众号: 2 次
  - 【众鲤数据网】: 2 次
  - 官网https://zldatas.com: 2 次
----------------------------------------

In [6]:
trash_columns = ['Unnamed: 10', '更多数据请关注公众号', 'Unnamed: 12','Unnamed: 13']
df.drop(columns=trash_columns, inplace=True)

In [7]:
print(f"now the columns are {df.columns}")

now the columns are Index(['级别', '产业', '产业园名称', '简介', '位置', '经度', '纬度', '省份', '城市', '区县'], dtype='object')

### Housing price

In [8]:
community_path = '/mnt/data/raydata/房产/Housing_Sale_Listing_Rent/community_p/community.parquet'
community = pd.read_parquet(community_path)
Display(community)

Shape: (317229, 28)
Index(['名称', '城市', '区县', '板块', '参考均价', '环线位置', '小区地址', '物业类别', '建筑年代', '开发商',
       '房屋总数', '楼栋总数', '物业公司', '绿 化 率', '容 积 率', '物 业 费', '建筑结构', '物业办公电话',
       '产权描述', '供水', '供暖', '供电', '燃气费', '供热费', '停车位', '停车费用', 'baidu_coord_x',
       'baidu_coord_y'],
      dtype='object')

               Missing  Unique    Dtype
名称                   0  278183   object
城市                   0      97   object
区县                   0    1020   object
板块                1243    5104   object
参考均价             77819   46637  float64
环线位置            263662      32   object
小区地址                12  301569   object
物业类别              9056    1372   object
建筑年代            123145    2603   object
开发商             132682   47763   object
房屋总数                76    6035   object
楼栋总数                66     523   object
物业公司            150734   39031   object
绿 化 率           107739    2343   object
容 积 率           106252    1342  float64
物 业 费           111916    9856   object
建筑结构             71152      15   object
物业办公电话          270728   18847   object
产权描述              9689    1496   object
供水               85941       3   object
供暖              183151       7   object
供电               83671       3   object
燃气费             117869    6131   object
供热费             228069    3579   object
停车位             124146    4735  float64
停车费用            135166    3799   object
baidu_coord_x        0  314556  float64
baidu_coord_y        0  314183  float64

【col: 名称】
  - 阳光花园: 64 次
  - 幸福家园: 63 次
  - 锦绣花园: 59 次
  - 粮食局宿舍: 42 次
  - 和谐家园: 41 次
----------------------------------------
【col: 城市】
  - 上海: 22092 次
  - 成都: 18260 次
  - 北京: 10945 次
  - 重庆: 10104 次
  - 苏州: 8625 次
----------------------------------------
【col: 区县】
  - 浦东: 3659 次
  - 顺德: 2216 次
  - 城关区: 2083 次
  - 鼓楼区: 2011 次
  - 金水: 1893 次
----------------------------------------
【col: 板块】
  - 老城区: 2106 次
  - 火车站: 1624 次
  - 魏都区: 1113 次
  - 都江堰: 1101 次
  - 海城区: 1060 次
----------------------------------------
【col: 参考均价】
  - 60000.0: 57 次
  - 50000.0: 51 次
  - 55000.0: 43 次
  - 68000.0: 41 次
  - 40000.0: 38 次
----------------------------------------
【col: 环线位置】
  - 外环外: 8494 次
  - 内环内: 7878 次
  - 二至三环: 6307 次
  - 内环至中环: 4184 次
  - 中环至外环: 3638 次
----------------------------------------
【col: 小区地址】
  - 兴华中路: 56 次
  - 太极大道: 50 次
  - 浔峰洲路8号: 37 次
  - 顺江大道: 34 次
  - 黎明路: 33 次
----------------------------------------
【col: 物业类别】
  - 普通住宅: 211943 次
  - 普通住宅/底商: 14259 次
  - 普通住宅/别墅: 10379 次
  - 普通住宅/商业/底商: 8421 次
  - 普通住宅/商业: 8348 次
----------------------------------------
【col: 建筑年代】
  - 2000年: 6292 次
  - 1998年: 4064 次
  - 1995年: 2804 次
  - 2005年: 2688 次
  - 1999年: 2418 次
----------------------------------------
【col: 开发商】
  - 无开发商: 18551 次
  - 无: 6910 次
  - 陕西亿润经贸有限公司: 3315 次
  - 重庆汇东房地产开发有限公司: 2835 次
  - 物业和度娘都不知道开发商名称: 2033 次
----------------------------------------
【col: 房屋总数】
  - 1户: 12901 次
  - 2户: 5096 次
  - 24户: 3656 次
  - 36户: 3232 次
  - 48户: 3175 次
----------------------------------------
【col: 楼栋总数】
  - 1栋: 78373 次
  - 2栋: 36822 次
  - 3栋: 25672 次
  - 4栋: 20412 次
  - 5栋: 15426 次
----------------------------------------
【col: 物业公司】
  - 无物业管理服务: 11009 次
  - 业主自筹物业: 6282 次
  - 街道办事处（居委会）代管物业: 5808 次
  - 私人承办物业: 2122 次
  - 小区物业: 1931 次
----------------------------------------
【col: 绿 化 率】
  - 30%: 47345 次
  - 35%: 27593 次
  - 20%: 23248 次
  - 10%: 14883 次
  - 40%: 13593 次
----------------------------------------
【col: 容 积 率】
  - 2.0: 28779 次
  - 3.0: 16786 次
  - 1.5: 12475 次
  - 2.5: 11472 次
  - 1.0: 11066 次
----------------------------------------
【col: 物 业 费】
  - 0.5元/月/㎡: 21464 次
  - 1元/月/㎡: 13911 次
  - 1.2元/月/㎡: 10067 次
  - 0.8元/月/㎡: 9540 次
  - 1.5元/月/㎡: 8297 次
----------------------------------------
【col: 建筑结构】
  - 板楼: 119530 次
  - 塔板结合: 34985 次
  - 塔楼: 26571 次
  - 板楼/塔板结合: 22147 次
  - 塔楼/板楼: 14895 次
----------------------------------------
【col: 物业办公电话】
  - 无: 20954 次
  - 暂无资料: 492 次
  - 暂无: 269 次
  - -: 259 次
  - 022-27022093: 110 次
----------------------------------------
【col: 产权描述】
  - 商品房: 222032 次
  - 商品房/使用权: 12376 次
  - 商品房/私产: 10485 次
  - 商品房/已购公房: 9394 次
  - 商品房/房改房: 6117 次
----------------------------------------
【col: 供水】
  - 民水: 189994 次
  - 商水/民水: 34414 次
  - 商水: 6880 次
----------------------------------------
【col: 供暖】
  - 集中供暖: 75336 次
  - 自采暖: 49137 次
  - 集中供暖/自采暖: 8270 次
  - 无供暖: 918 次
  - 自采暖/无供暖: 369 次
----------------------------------------
【col: 供电】
  - 民电: 191088 次
  - 商电/民电: 35674 次
  - 商电: 6796 次
----------------------------------------
【col: 燃气费】
  - 3元/m³: 13588 次
  - 2.61元/m³: 10025 次
  - 3.5元/m³: 6700 次
  - 3.45元/m³: 6431 次
  - 1.98元/m³: 6425 次
----------------------------------------
【col: 供热费】
  - 25元/㎡: 8222 次
  - 30元/㎡: 7198 次
  - 22元/㎡: 6095 次
  - 30.4元/㎡: 4161 次
  - 26元/㎡: 4059 次
----------------------------------------
【col: 停车位】
  - 100.0: 13648 次
  - 200.0: 13076 次
  - 50.0: 9317 次
  - 300.0: 8328 次
  - 20.0: 6193 次
----------------------------------------
【col: 停车费用】
  - 150: 21294 次
  - 300: 20479 次
  - 200: 19364 次
  - 100: 17829 次
  - 暂无: 15528 次
----------------------------------------
【col: baidu_coord_x】
  - 115.9501: 30 次
  - 115.950135: 21 次
  - 115.8989: 17 次
  - 115.9101: 15 次
  - 115.922: 13 次
----------------------------------------
【col: baidu_coord_y】
  - 28.55: 30 次
  - 28.550035: 21 次
  - 28.6573: 16 次
  - 28.6924: 15 次
  - 28.6366: 13 次
----------------------------------------

# 2.Data Cleaning

In [9]:
df_cleaned = df.dropna(subset=['经度','纬度'])
community_cleaned = community.dropna(subset=['baidu_coord_x','baidu_coord_y','参考均价'])
community_cleaned = community_cleaned.rename(columns={'baidu_coord_x':'x','baidu_coord_y':'y','参考均价':'price'})
df_cleaned = df_cleaned.rename(columns={'经度':'x','纬度':'y'})

In [10]:
sub_community = community_cleaned[['x', 'y','price','城市','区县','建筑结构']].copy()
sub_df = df_cleaned[['x', 'y']].copy()

In [11]:
# according to the distance to find the nearest park for each community
import numpy as np
from sklearn.neighbors import NearestNeighbors

park_coords_rad = np.radians(sub_df[['x', 'y']])
house_coords_rad = np.radians(sub_community[['x', 'y']])

model = NearestNeighbors(n_neighbors=1, algorithm='ball_tree', metric='haversine')
model.fit(park_coords_rad)

distances_rad, indices = model.kneighbors(house_coords_rad)

sub_community['nearest_park_dist_km'] = distances_rad.flatten() * 6371

sub_community['nearest_park_index'] = sub_df.index[indices.flatten()]
print(sub_community[['x', 'y', 'nearest_park_index', 'nearest_park_dist_km']].head())

             x          y  nearest_park_index  nearest_park_dist_km
1   104.110757  30.686905               11977              0.488280
7   104.113817  30.696091                5638              0.170696
10  104.109100  30.685527               10670              0.365403
11  104.119772  30.693906                5646              0.530374
12  104.113288  30.690898                5638              0.195805

In [12]:
sub_community['log_price'] = np.log(sub_community['price'] + 1)

# 3.Feature Engineering

In [13]:
sub_community.columns

Index(['x', 'y', 'price', '城市', '区县', '建筑结构', 'nearest_park_dist_km',
       'nearest_park_index', 'log_price'],
      dtype='object')

In [14]:
sub_community['区县'].value_counts()

区县
城关区    1765
顺德     1753
金水     1715
鼓楼区    1709
金牛     1699
       ...
阜平县       1
徐闻县       1
孝昌县       1
松江        1
永寿县       1
Name: count, Length: 911, dtype: int64

In [15]:
# use matplotlib to plot the price of Beijing on the real map
beijing_data = sub_community[sub_community['城市'] == '北京']

In [16]:
beijing_data

,x,y,price,城市,区县,建筑结构,nearest_park_dist_km,nearest_park_index,log_price
9044,116.010238,40.469447,23521.0,北京,延庆,板楼/塔板结合,1.397487,29851,10.065691
9051,115.976080,40.465065,17522.0,北京,延庆,板楼,0.428653,793,9.771270
9071,116.048603,40.490921,20361.0,北京,延庆,板楼/塔板结合,5.782860,29851,9.921426
9072,115.984581,40.366166,31510.0,北京,延庆,塔楼/板楼/塔板结合,0.767934,10014,10.358092
9073,115.986143,40.365768,12108.0,北京,延庆,塔楼/板楼/塔板结合,0.930378,10014,9.401704
...,...,...,...,...,...,...,...,...,...
313539,116.360631,39.933276,128426.0,北京,西城,板楼/平房,0.851190,2479,11.763116
313544,116.399989,39.888473,107869.0,北京,西城,None,0.381267,10409,11.588682
313545,116.358677,39.942039,132378.0,北京,西城,塔楼/板楼/塔板结合,0.589094,8787,11.793424
313546,116.360722,39.933626,135003.0,北京,西城,板楼,0.863517,2479,11.813060
313556,116.361350,39.938574,123159.0,北京,西城,塔楼/板楼/塔板结合,0.752401,14182,11.721240